apiVersion: v1
kind: Secret
metadata:
  name: evalai-secrets
type: Opaque
data:
  database-url: <base64-encoded-database-url>
  nextauth-secret: <base64-encoded-nextauth-secret>
  google-client-id: <base64-encoded-google-client-id>
  google-client-secret: <base64-encoded-google-client-secret>
  github-client-id: <base64-encoded-github-client-id>
  github-client-secret: <base64-encoded-github-client-secret>
  aws-access-key-id: <base64-encoded-aws-access-key-id>
  aws-secret-access-key: <base64-encoded-aws-secret-access-key>
  aws-region: <base64-encoded-aws-region>
  aws-bucket-name: <base64-encoded-aws-bucket-name>
  file-encryption-key: <base64-encoded-file-encryption-key>

